default: install start

install:
	@yarn install

start:
	@HOST=0.0.0.0 BROWSER=none PORT=3001 REACT_APP_KEYCLOAK_URL=https://login.wkspower.local REACT_APP_API_URL=https://api.wkspower.local REACT_APP_EMAIL_URL=http://localhost:8083 yarn start