/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wks.caseengine.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ActivityInstance
 */
public class ActivityInstanceTest {
    private final ActivityInstance model = new ActivityInstance();

    /**
     * Model tests for ActivityInstance
     */
    @Test
    public void testActivityInstance() {
        // TODO: test ActivityInstance
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'activityId'
     */
    @Test
    public void activityIdTest() {
        // TODO: test activityId
    }

    /**
     * Test the property 'activityType'
     */
    @Test
    public void activityTypeTest() {
        // TODO: test activityType
    }

    /**
     * Test the property 'childActivityInstances'
     */
    @Test
    public void childActivityInstancesTest() {
        // TODO: test childActivityInstances
    }

}
