/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for CaseInstance
 */
public class CaseInstanceTest {
	private final CaseInstance model = new CaseInstance();

	/**
	 * Model tests for CaseInstance
	 */
	@Test
	public void testCaseInstance() {
		// TODO: test CaseInstance
	}

	/**
	 * Test the property 'getId'
	 */
	@Test
	public void getIdTest() {
		// TODO: test getId
	}

	/**
	 * Test the property 'businessKey'
	 */
	@Test
	public void businessKeyTest() {
		// TODO: test businessKey
	}

	/**
	 * Test the property 'caseDefinitionId'
	 */
	@Test
	public void caseDefinitionIdTest() {
		// TODO: test caseDefinitionId
	}

	/**
	 * Test the property 'stage'
	 */
	@Test
	public void stageTest() {
		// TODO: test stage
	}

	/**
	 * Test the property 'caseOwner'
	 */
	@Test
	public void caseOwnerTest() {
		// TODO: test caseOwner
	}

	/**
	 * Test the property 'caseOwnerName'
	 */
	@Test
	public void caseOwnerNameTest() {
		// TODO: test caseOwnerName
	}

	/**
	 * Test the property 'comments'
	 */
	@Test
	public void commentsTest() {
		// TODO: test comments
	}

	/**
	 * Test the property 'documents'
	 */
	@Test
	public void documentsTest() {
		// TODO: test documents
	}

	/**
	 * Test the property 'attributes'
	 */
	@Test
	public void attributesTest() {
		// TODO: test attributes
	}

	/**
	 * Test the property 'status'
	 */
	@Test
	public void statusTest() {
		// TODO: test status
	}

	/**
	 * Test the property 'id'
	 */
	@Test
	public void idTest() {
		// TODO: test id
	}

}
