/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for CaseDefinition
 */
public class CaseDefinitionTest {
	private final CaseDefinition model = new CaseDefinition();

	/**
	 * Model tests for CaseDefinition
	 */
	@Test
	public void testCaseDefinition() {
		// TODO: test CaseDefinition
	}

	/**
	 * Test the property 'id'
	 */
	@Test
	public void idTest() {
		// TODO: test id
	}

	/**
	 * Test the property 'name'
	 */
	@Test
	public void nameTest() {
		// TODO: test name
	}

	/**
	 * Test the property 'formKey'
	 */
	@Test
	public void formKeyTest() {
		// TODO: test formKey
	}

	/**
	 * Test the property 'stagesLifecycleProcessKey'
	 */
	@Test
	public void stagesLifecycleProcessKeyTest() {
		// TODO: test stagesLifecycleProcessKey
	}

	/**
	 * Test the property 'stages'
	 */
	@Test
	public void stagesTest() {
		// TODO: test stages
	}

	/**
	 * Test the property 'kanbanConfig'
	 */
	@Test
	public void kanbanConfigTest() {
		// TODO: test kanbanConfig
	}

	/**
	 * Test the property 'deployed'
	 */
	@Test
	public void deployedTest() {
		// TODO: test deployed
	}

}
