/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for CaseAttribute
 */
public class CaseAttributeTest {
	private final CaseAttribute model = new CaseAttribute();

	/**
	 * Model tests for CaseAttribute
	 */
	@Test
	public void testCaseAttribute() {
		// TODO: test CaseAttribute
	}

	/**
	 * Test the property 'name'
	 */
	@Test
	public void nameTest() {
		// TODO: test name
	}

	/**
	 * Test the property 'value'
	 */
	@Test
	public void valueTest() {
		// TODO: test value
	}

	/**
	 * Test the property 'type'
	 */
	@Test
	public void typeTest() {
		// TODO: test type
	}

}
