/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for CaseDocument
 */
public class CaseDocumentTest {
	private final CaseDocument model = new CaseDocument();

	/**
	 * Model tests for CaseDocument
	 */
	@Test
	public void testCaseDocument() {
		// TODO: test CaseDocument
	}

	/**
	 * Test the property 'name'
	 */
	@Test
	public void nameTest() {
		// TODO: test name
	}

	/**
	 * Test the property 'type'
	 */
	@Test
	public void typeTest() {
		// TODO: test type
	}

	/**
	 * Test the property 'size'
	 */
	@Test
	public void sizeTest() {
		// TODO: test size
	}

	/**
	 * Test the property 'base64'
	 */
	@Test
	public void base64Test() {
		// TODO: test base64
	}

}
