/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for Form
 */
public class FormTest {
	private final Form model = new Form();

	/**
	 * Model tests for Form
	 */
	@Test
	public void testForm() {
		// TODO: test Form
	}

	/**
	 * Test the property 'key'
	 */
	@Test
	public void keyTest() {
		// TODO: test key
	}

	/**
	 * Test the property 'title'
	 */
	@Test
	public void titleTest() {
		// TODO: test title
	}

	/**
	 * Test the property 'toolTip'
	 */
	@Test
	public void toolTipTest() {
		// TODO: test toolTip
	}

	/**
	 * Test the property 'structure'
	 */
	@Test
	public void structureTest() {
		// TODO: test structure
	}

}
