/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wks.caseengine.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wks.caseengine.client.model.JsonArray;
import com.wks.caseengine.client.model.JsonNull;
import com.wks.caseengine.client.model.JsonPrimitive;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JsonObject
 */
public class JsonObjectTest {
    private final JsonObject model = new JsonObject();

    /**
     * Model tests for JsonObject
     */
    @Test
    public void testJsonObject() {
        // TODO: test JsonObject
    }

    /**
     * Test the property 'asBoolean'
     */
    @Test
    public void asBooleanTest() {
        // TODO: test asBoolean
    }

    /**
     * Test the property 'asDouble'
     */
    @Test
    public void asDoubleTest() {
        // TODO: test asDouble
    }

    /**
     * Test the property 'asInt'
     */
    @Test
    public void asIntTest() {
        // TODO: test asInt
    }

    /**
     * Test the property 'asLong'
     */
    @Test
    public void asLongTest() {
        // TODO: test asLong
    }

    /**
     * Test the property 'asString'
     */
    @Test
    public void asStringTest() {
        // TODO: test asString
    }

    /**
     * Test the property 'asJsonArray'
     */
    @Test
    public void asJsonArrayTest() {
        // TODO: test asJsonArray
    }

    /**
     * Test the property 'asJsonObject'
     */
    @Test
    public void asJsonObjectTest() {
        // TODO: test asJsonObject
    }

    /**
     * Test the property 'asJsonPrimitive'
     */
    @Test
    public void asJsonPrimitiveTest() {
        // TODO: test asJsonPrimitive
    }

    /**
     * Test the property 'jsonArray'
     */
    @Test
    public void jsonArrayTest() {
        // TODO: test jsonArray
    }

    /**
     * Test the property 'jsonObject'
     */
    @Test
    public void jsonObjectTest() {
        // TODO: test jsonObject
    }

    /**
     * Test the property 'jsonPrimitive'
     */
    @Test
    public void jsonPrimitiveTest() {
        // TODO: test jsonPrimitive
    }

    /**
     * Test the property 'jsonNull'
     */
    @Test
    public void jsonNullTest() {
        // TODO: test jsonNull
    }

    /**
     * Test the property 'asJsonNull'
     */
    @Test
    public void asJsonNullTest() {
        // TODO: test asJsonNull
    }

    /**
     * Test the property 'asNumber'
     */
    @Test
    public void asNumberTest() {
        // TODO: test asNumber
    }

    /**
     * Test the property 'asFloat'
     */
    @Test
    public void asFloatTest() {
        // TODO: test asFloat
    }

    /**
     * Test the property 'asByte'
     */
    @Test
    public void asByteTest() {
        // TODO: test asByte
    }

    /**
     * Test the property 'asCharacter'
     */
    @Test
    public void asCharacterTest() {
        // TODO: test asCharacter
    }

    /**
     * Test the property 'asBigDecimal'
     */
    @Test
    public void asBigDecimalTest() {
        // TODO: test asBigDecimal
    }

    /**
     * Test the property 'asBigInteger'
     */
    @Test
    public void asBigIntegerTest() {
        // TODO: test asBigInteger
    }

    /**
     * Test the property 'asShort'
     */
    @Test
    public void asShortTest() {
        // TODO: test asShort
    }

}
