/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for ProcessDefinition
 */
public class ProcessDefinitionTest {
	private final ProcessDefinition model = new ProcessDefinition();

	/**
	 * Model tests for ProcessDefinition
	 */
	@Test
	public void testProcessDefinition() {
		// TODO: test ProcessDefinition
	}

	/**
	 * Test the property 'bpmEngineId'
	 */
	@Test
	public void bpmEngineIdTest() {
		// TODO: test bpmEngineId
	}

}
