/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for ProcessMessage
 */
public class ProcessMessageTest {
	private final ProcessMessage model = new ProcessMessage();

	/**
	 * Model tests for ProcessMessage
	 */
	@Test
	public void testProcessMessage() {
		// TODO: test ProcessMessage
	}

	/**
	 * Test the property 'tenantId'
	 */
	@Test
	public void tenantIdTest() {
		// TODO: test tenantId
	}

	/**
	 * Test the property 'messageName'
	 */
	@Test
	public void messageNameTest() {
		// TODO: test messageName
	}

	/**
	 * Test the property 'businessKey'
	 */
	@Test
	public void businessKeyTest() {
		// TODO: test businessKey
	}

	/**
	 * Test the property 'processVariables'
	 */
	@Test
	public void processVariablesTest() {
		// TODO: test processVariables
	}

}
