/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for RecordType
 */
public class RecordTypeTest {
	private final RecordType model = new RecordType();

	/**
	 * Model tests for RecordType
	 */
	@Test
	public void testRecordType() {
		// TODO: test RecordType
	}

	/**
	 * Test the property 'id'
	 */
	@Test
	public void idTest() {
		// TODO: test id
	}

	/**
	 * Test the property 'fields'
	 */
	@Test
	public void fieldsTest() {
		// TODO: test fields
	}

}
