/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.model;

import org.junit.Test;

/**
 * Model tests for Task
 */
public class TaskTest {
	private final Task model = new Task();

	/**
	 * Model tests for Task
	 */
	@Test
	public void testTask() {
		// TODO: test Task
	}

	/**
	 * Test the property 'id'
	 */
	@Test
	public void idTest() {
		// TODO: test id
	}

	/**
	 * Test the property 'owner'
	 */
	@Test
	public void ownerTest() {
		// TODO: test owner
	}

	/**
	 * Test the property 'assignee'
	 */
	@Test
	public void assigneeTest() {
		// TODO: test assignee
	}

	/**
	 * Test the property 'name'
	 */
	@Test
	public void nameTest() {
		// TODO: test name
	}

	/**
	 * Test the property 'description'
	 */
	@Test
	public void descriptionTest() {
		// TODO: test description
	}

	/**
	 * Test the property 'priority'
	 */
	@Test
	public void priorityTest() {
		// TODO: test priority
	}

	/**
	 * Test the property 'created'
	 */
	@Test
	public void createdTest() {
		// TODO: test created
	}

	/**
	 * Test the property 'due'
	 */
	@Test
	public void dueTest() {
		// TODO: test due
	}

	/**
	 * Test the property 'followUp'
	 */
	@Test
	public void followUpTest() {
		// TODO: test followUp
	}

	/**
	 * Test the property 'tenantId'
	 */
	@Test
	public void tenantIdTest() {
		// TODO: test tenantId
	}

	/**
	 * Test the property 'executionId'
	 */
	@Test
	public void executionIdTest() {
		// TODO: test executionId
	}

	/**
	 * Test the property 'processInstanceId'
	 */
	@Test
	public void processInstanceIdTest() {
		// TODO: test processInstanceId
	}

	/**
	 * Test the property 'processDefinitionId'
	 */
	@Test
	public void processDefinitionIdTest() {
		// TODO: test processDefinitionId
	}

	/**
	 * Test the property 'caseExecutionId'
	 */
	@Test
	public void caseExecutionIdTest() {
		// TODO: test caseExecutionId
	}

	/**
	 * Test the property 'caseInstanceId'
	 */
	@Test
	public void caseInstanceIdTest() {
		// TODO: test caseInstanceId
	}

	/**
	 * Test the property 'caseDefinitionId'
	 */
	@Test
	public void caseDefinitionIdTest() {
		// TODO: test caseDefinitionId
	}

	/**
	 * Test the property 'taskDefinitionKey'
	 */
	@Test
	public void taskDefinitionKeyTest() {
		// TODO: test taskDefinitionKey
	}

	/**
	 * Test the property 'formKey'
	 */
	@Test
	public void formKeyTest() {
		// TODO: test formKey
	}

}
