/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.api;

import org.junit.Ignore;
import org.junit.Test;

import com.wks.caseengine.client.model.CaseDocument;
import com.wks.caseengine.client.model.CaseInstance;
import com.wks.caseengine.client.model.Comment;

/**
 * API tests for CaseInstanceApi
 */
@Ignore
public class CaseInstanceApiTest {

	private final CaseInstanceApi api = new CaseInstanceApi();

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void delete3Test() {
		String businessKey = null;
		api.delete3(businessKey);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void deleteCommentTest() {
		String businessKey = null;
		String commentId = null;
		api.deleteComment(businessKey, commentId);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void find6Test() {
		String status = null;
		String caseDefinitionId = null;
		String before = null;
		String after = null;
		String sort = null;
		String limit = null;
		Object response = api.find6(status, caseDefinitionId, before, after, sort, limit);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void get5Test() {
		String businessKey = null;
		CaseInstance response = api.get5(businessKey);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void save4Test() {
		CaseInstance caseInstance = null;
		CaseInstance response = api.save4(caseInstance);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void saveCommentTest() {
		String businessKey = null;
		Comment comment = null;
		api.saveComment(businessKey, comment);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void saveDocumentTest() {
		String businessKey = null;
		CaseDocument caseDocument = null;
		api.saveDocument(businessKey, caseDocument);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void udpateCommentTest() {
		String businessKey = null;
		String commentId = null;
		Comment comment = null;
		api.udpateComment(businessKey, commentId, comment);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void update3Test() {
		String businessKey = null;
		CaseInstance caseInstance = null;
		api.update3(businessKey, caseInstance);

		// TODO: test validations
	}

}
