/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.api;

import org.junit.Ignore;
import org.junit.Test;

import com.wks.caseengine.client.model.JsonObject;

/**
 * API tests for DataImportControllerApi
 */
@Ignore
public class DataImportControllerApiTest {

	private final DataImportControllerApi api = new DataImportControllerApi();

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void importDataTest() {
		JsonObject jsonObject = null;
		api.importData(jsonObject);

		// TODO: test validations
	}

}
