/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import com.wks.caseengine.client.model.JsonObject;

/**
 * API tests for RecordControllerApi
 */
@Ignore
public class RecordControllerApiTest {

	private final RecordControllerApi api = new RecordControllerApi();

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void deleteTest() {
		String recordTypeId = null;
		String id = null;
		api.delete(recordTypeId, id);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void find1Test() {
		String recordTypeId = null;
		List<JsonObject> response = api.find1(recordTypeId);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void getTest() {
		String recordTypeId = null;
		String id = null;
		JsonObject response = api.get(recordTypeId, id);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void saveTest() {
		String recordTypeId = null;
		JsonObject jsonObject = null;
		api.save(recordTypeId, jsonObject);

		// TODO: test validations
	}

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void updateTest() {
		String recordTypeId = null;
		String id = null;
		JsonObject jsonObject = null;
		api.update(recordTypeId, id, jsonObject);

		// TODO: test validations
	}

}
