/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wks.caseengine.client.api;

import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for VariablesApi
 */
@Ignore
public class VariablesApiTest {

	private final VariablesApi api = new VariablesApi();

	/**
	 *
	 *
	 *
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void findVariablesTest() {
		String processInstanceId = null;
		String response = api.findVariables(processInstanceId);

		// TODO: test validations
	}

}
