export const overAllAOpResponse =
  //OVERALL AOP
  {
    code: 200,
    message: 'Data fetched successfully',
    data: {
      mcuNormsValueDTOList: [
        // B. Fresh Feeds to Reactor
        {
          id: 'FCC-B1',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Hydro treated VGO',
        },
        {
          id: 'FCC-B2',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Imported LSWR/LSFO/CRUDE/External Feed',
        },
        {
          id: 'FCC-B3',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'HAGO',
        },
        {
          id: 'FCC-B4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'LVGO',
        },
        {
          id: 'FCC-B5',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Coker LCN',
        },
        {
          id: 'FCC-B6',
          april: 0.0,
          may: 0.0,
          june: 0.0,
          july: 0.0,
          august: 0.0,
          september: 0.0,
          october: 0.0,
          november: 0.0,
          december: 0.0,
          january: 0.0,
          february: 0.0,
          march: 0.0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Total fresh feeds',
        },

        // C. Feed Specifications
        {
          id: 'FCC-C1',
          april: 0.0,
          may: 0.0,
          june: 0.0,
          july: 0.0,
          august: 0.0,
          september: 0.0,
          october: 0.0,
          november: 0.0,
          december: 0.0,
          january: 0.0,
          february: 0.0,
          march: 0.0,
          financialYear: '2025-26',
          remarks: 'Placeholder for UOP K',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'Number',
          isEditable: true,
          productName: 'UOP K',
        },
        {
          id: 'FCC-C2',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'g/ml',
          isEditable: true,
          productName: 'Density',
        },
        {
          id: 'FCC-C3',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Nitrogen (total)',
        },
        {
          id: 'FCC-C4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'wt%',
          isEditable: true,
          productName: 'Conradson Carbon',
        },
        {
          id: 'FCC-C5',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Nickel',
        },
        {
          id: 'FCC-C6',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Vanadium',
        },
        {
          id: 'FCC-C7',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Sodium',
        },

        // E. Product Yields
        {
          id: 'FCC-E1',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Fuel Gas',
        },
        {
          id: 'FCC-E2',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Propylene (ex FCC)',
        },
        {
          id: 'FCC-E3',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'LPG',
        },
        {
          id: 'FCC-E4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Light Naphtha',
        },
        {
          id: 'FCC-E5',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Heart Cut Naphtha',
        },
        {
          id: 'FCC-E6',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Heavy Cracked Naphtha (HCN)',
        },
        {
          id: 'FCC-E7',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Light Cycle Oil (LCO)',
        },
        {
          id: 'FCC-E8',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Clarified Slurry Oil (CSO)',
        },
        {
          id: 'FCC-E9',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Coke',
        },
        {
          id: 'FCC-E10',
          april: 0.0,
          may: 0.0,
          june: 0.0,
          july: 0.0,
          august: 0.0,
          september: 0.0,
          october: 0.0,
          november: 0.0,
          december: 0.0,
          january: 0.0,
          february: 0.0,
          march: 0.0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Total',
        },

        // F. Utilities
        {
          id: '310027910',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'KWh/T',
          isEditable: true,
          productName: 'Power Import',
        },
        {
          id: '310027912',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'M3/T',
          isEditable: true,
          productName: 'Cooling Water',
        },
        {
          id: '310027972',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'HP BFW',
        },
        {
          id: 'FCC-F4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'MP BFW',
        },
        {
          id: '310027939',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Net HP Steam Import',
        },
        {
          id: '310027940',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Net MP Steam Import',
        },
        {
          id: '310027965',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Net LP steam Export',
        },
        {
          id: '310027968',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Cold Clean Condensate',
        },
        {
          id: '310027923',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Condensate export',
        },
        {
          id: '310027928',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Utility water',
        },
        {
          id: '310027904',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'NM3/T',
          isEditable: true,
          productName: 'Compressed Air',
        },
        {
          id: '310027971',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'NM3/T',
          isEditable: true,
          productName: 'Nitrogen',
        },
        {
          id: '310028423',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'M3/T',
          isEditable: true,
          productName: 'Desal',
        },
        {
          id: '1000000091',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'Kg/KT',
          isEditable: true,
          productName: 'CHEM SODIUM HYDROXIDE (CAUSTIC)',
        },

        // G. Catalyst and Chemicals
        {
          id: '1000028034',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM MAXTREAT 3223 SJ',
        },
        {
          id: '1000000286',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM MAX-AMINE 70B',
        },
        {
          id: '1000029118',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: 'Dry basis',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM CAT RELIANCE FCC1 X11D2A',
        },
        {
          id: '1000021904',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM CAT OLEFINS ULTRA MZ ADDITIVE',
        },
        {
          id: '1000000267',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM CAT CP5/COP550/KOC-15 COMB PROM',
        },
        {
          id: '1000023561',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'VASUFLOC - 4410',
        },
        {
          id: '1000032074',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'Kg/kT',
          isEditable: true,
          productName: 'VASUFLOC-1012C',
        },

        // H. TSRF
        {
          id: 'FCC-H1',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'TSRF',
          normParameterTypeDisplayName: 'TSRF',
          UOM: 'TSRF/kT',
          isEditable: true,
          productName: 'TSRF',
        },
      ],
      aopCalculation: [],
    },
  }

export const steadyStateConsumptionResponse =
  //STEAD STA ENORMS

  {
    code: 200,
    message: 'Data fetched successfully',
    data: {
      mcuNormsValueDTOList: [
        // B. Fresh Feeds to Reactor
        {
          id: 'FCC-B1',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Hydro treated VGO',
        },
        {
          id: 'FCC-B2',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Imported LSWR/LSFO/CRUDE/External Feed',
        },
        {
          id: 'FCC-B3',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'HAGO',
        },
        {
          id: 'FCC-B4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'LVGO',
        },
        {
          id: 'FCC-B5',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Coker LCN',
        },
        {
          id: 'FCC-B6',
          april: 0.0,
          may: 0.0,
          june: 0.0,
          july: 0.0,
          august: 0.0,
          september: 0.0,
          october: 0.0,
          november: 0.0,
          december: 0.0,
          january: 0.0,
          february: 0.0,
          march: 0.0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fresh Feeds to Reactor',
          normParameterTypeDisplayName: 'Fresh Feeds to Reactor',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Total fresh feeds',
        },

        // C. Feed Specifications
        {
          id: 'FCC-C1',
          april: 0.0,
          may: 0.0,
          june: 0.0,
          july: 0.0,
          august: 0.0,
          september: 0.0,
          october: 0.0,
          november: 0.0,
          december: 0.0,
          january: 0.0,
          february: 0.0,
          march: 0.0,
          financialYear: '2025-26',
          remarks: 'Placeholder for UOP K',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'Number',
          isEditable: true,
          productName: 'UOP K',
        },
        {
          id: 'FCC-C2',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'g/ml',
          isEditable: true,
          productName: 'Density',
        },
        {
          id: 'FCC-C3',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Nitrogen (total)',
        },
        {
          id: 'FCC-C4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'wt%',
          isEditable: true,
          productName: 'Conradson Carbon',
        },
        {
          id: 'FCC-C5',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Nickel',
        },
        {
          id: 'FCC-C6',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Vanadium',
        },
        {
          id: 'FCC-C7',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed Specifications',
          normParameterTypeDisplayName: 'Feed Specifications',
          UOM: 'ppmwt',
          isEditable: true,
          productName: 'Sodium',
        },

        // E. Product Yields
        {
          id: 'FCC-E1',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Fuel Gas',
        },
        {
          id: 'FCC-E2',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Propylene (ex FCC)',
        },
        {
          id: 'FCC-E3',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'LPG',
        },
        {
          id: 'FCC-E4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Light Naphtha',
        },
        {
          id: 'FCC-E5',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Heart Cut Naphtha',
        },
        {
          id: 'FCC-E6',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Heavy Cracked Naphtha (HCN)',
        },
        {
          id: 'FCC-E7',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Light Cycle Oil (LCO)',
        },
        {
          id: 'FCC-E8',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Clarified Slurry Oil (CSO)',
        },
        {
          id: 'FCC-E9',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Coke',
        },
        {
          id: 'FCC-E10',
          april: 0.0,
          may: 0.0,
          june: 0.0,
          july: 0.0,
          august: 0.0,
          september: 0.0,
          october: 0.0,
          november: 0.0,
          december: 0.0,
          january: 0.0,
          february: 0.0,
          march: 0.0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Product Yields',
          normParameterTypeDisplayName: 'Product Yields',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Total',
        },

        // F. Utilities
        {
          id: '310027910',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'KWh/T',
          isEditable: true,
          productName: 'Power Import',
        },
        {
          id: '310027912',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'M3/T',
          isEditable: true,
          productName: 'Cooling Water',
        },
        {
          id: '310027972',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'HP BFW',
        },
        {
          id: 'FCC-F4',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'MP BFW',
        },
        {
          id: '310027939',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Net HP Steam Import',
        },
        {
          id: '310027940',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Net MP Steam Import',
        },
        {
          id: '310027965',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Net LP steam Export',
        },
        {
          id: '310027968',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Cold Clean Condensate',
        },
        {
          id: '310027923',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Condensate export',
        },
        {
          id: '310027928',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'T/T',
          isEditable: true,
          productName: 'Utility water',
        },
        {
          id: '310027904',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'NM3/T',
          isEditable: true,
          productName: 'Compressed Air',
        },
        {
          id: '310027971',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'NM3/T',
          isEditable: true,
          productName: 'Nitrogen',
        },
        {
          id: '310028423',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Utilities',
          normParameterTypeDisplayName: 'Utilities',
          UOM: 'M3/T',
          isEditable: true,
          productName: 'Desal',
        },
        {
          id: '1000000091',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'Kg/KT',
          isEditable: true,
          productName: 'CHEM SODIUM HYDROXIDE (CAUSTIC)',
        },

        // G. Catalyst and Chemicals
        {
          id: '1000028034',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM MAXTREAT 3223 SJ',
        },
        {
          id: '1000000286',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM MAX-AMINE 70B',
        },
        {
          id: '1000029118',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: 'Dry basis',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM CAT RELIANCE FCC1 X11D2A',
        },
        {
          id: '1000021904',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM CAT OLEFINS ULTRA MZ ADDITIVE',
        },
        {
          id: '1000000267',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'CHEM CAT CP5/COP550/KOC-15 COMB PROM',
        },
        {
          id: '1000023561',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'kg/kT',
          isEditable: true,
          productName: 'VASUFLOC - 4410',
        },
        {
          id: '1000032074',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst and Chemicals',
          normParameterTypeDisplayName: 'Catalyst and Chemicals',
          UOM: 'Kg/kT',
          isEditable: true,
          productName: 'VASUFLOC-1012C',
        },

        // H. TSRF
        {
          id: 'FCC-H1',
          april: 3.5,
          may: 3.5,
          june: 3.5,
          july: 3.5,
          august: 3.5,
          september: 3.5,
          october: 3.5,
          november: 3.5,
          december: 3.5,
          january: 3.5,
          february: 3.5,
          march: 3.5,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'TSRF',
          normParameterTypeDisplayName: 'TSRF',
          UOM: 'TSRF/kT',
          isEditable: true,
          productName: 'TSRF',
        },
      ],
      aopCalculation: [],
    },
  }

export const monthwiseProductionPlanResponse =
  //MONTH WISE PRODUCTION PLAN

  {
    code: 200,
    message: 'Data fetched successfully',
    data: {
      aopCalculation: [
        {
          id: 'd0b0e843-383f-4248-a97e-09cb3919a8ca',
          plantId: 'aacdbe12-c5f6-4b79-9c88-751169815b42',
          aopYear: '2025-26',
          isChanged: true,
          calculationScreen: 'production-aop',
          updatedScreen: 'shutdown-plan',
        },
      ],
      aopDTOList: [
        {
          id: '158B5A43-369A-4D48-8B7F-4DA9A15A6FED',
          jan: 14673.620599999998,
          feb: 13225.5872,
          march: 14641.6782,
          april: 17136.0,
          may: 14353.979599999999,
          june: 13836.228000000001,
          july: 14282.102999999997,
          aug: 14352.287,
          sep: 13934.807999999999,
          oct: 14198.521525,
          nov: 10416.739999999998,
          dec: 9443.228000000003,
          avgTPH: 165678.6875,
          materialFKId: '00DC05B1-9607-470E-A159-62497E0123E2',
          displayOrder: 1,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'VGO',
          type: 'product',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: 'EBC50FD2-A8E7-487F-8818-E36DC31E10C0',
          jan: 3429.1331999999998,
          feb: 3039.5456,
          march: 3318.2462,
          april: 3225.5879999999997,
          may: 3207.5638,
          june: 3259.506,
          july: 3284.4251999999997,
          aug: 3247.591,
          sep: 3192.7619999999997,
          oct: 3127.8820333333333,
          nov: 11151.582,
          dec: 2211.692,
          avgTPH: 39429.55859375,
          materialFKId: 'A061E050-0281-421F-81C1-B136CE2ED3F3',
          displayOrder: 2,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Diesel',
          type: 'product',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589D',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Kerosene',
          type: 'product',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589DM',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Slops',
          type: 'biproduct',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589DN',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Off Gas',
          type: 'biproduct',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589DO',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'H2S',
          type: 'biproduct',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
      ],
    },
  }

//Production and Norms Basis Constatnt
export const productionAndNormsBasisConstant = {
  code: 200,
  message: 'Data fetched successfully',
  data: [
    {
      NormParameter_FK_Id: '75E48C4B-873C-41AF-9EA6-50A2F6BB987F',
      // UOM: 'MT',
      isEditable: true,
      Remarks: '2',
      NormDisplayTypeName: 'Constant',
      DisplayName: 'Allocated Ethyelene Consumptions',
      AuditYear: '2026-27',
      ConstantValue: 0.07292,
      Name: 'A',
    },
    {
      NormParameter_FK_Id: 'C3ECFA4D-843A-4F16-A5B2-1C94B7C15F82',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT.',
      NormTypeName: 'Constant',
      DisplayName: 'BFWFeedTemperature',
      AuditYear: '2026-27',
      ConstantValue: 0.0625,
      Name: 'B',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285DA',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.06355,
      Name: 'D',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285DAP',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0588,
      Name: 'E',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285DAQ',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.05097,
      Name: 'F',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0533,
      Name: 'G',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.28571,
      Name: 'H',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.229,
      Name: 'I',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0625,
      Name: 'HpsConstant',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0588,
      Name: 'MpsConstant',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0533,
      Name: 'LpsConstant',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.229,
      Name: 'Power',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 10,
      Name: 'Tput',
    },
  ],
}

export const configurationAndReportManualEntryResponse =
  //COMMON CONFIGURATION SCRN + REPORT MANNUAL ENTRy
  {
    code: 200,
    message: 'Data fetched successfully',
    data: [
      // B. Fresh Feeds to Reactor
      {
        normParameterFKId: '11111111-1111-1111-1111-111111111111',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Fresh Feeds to Reactor',
        isEditable: true,
        productName: 'Hydro treated VGO',
      },
      {
        normParameterFKId: '11111111-1111-1111-1111-111111111112',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Fresh Feeds to Reactor',
        isEditable: true,
        productName: 'Imported LSWR/LSFO/CRUDE/External Feed',
      },
      {
        normParameterFKId: '11111111-1111-1111-1111-111111111113',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Fresh Feeds to Reactor',
        isEditable: true,
        productName: 'HAGO',
      },
      {
        normParameterFKId: '11111111-1111-1111-1111-111111111114',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Fresh Feeds to Reactor',
        isEditable: true,
        productName: 'LVGO',
      },
      {
        normParameterFKId: '11111111-1111-1111-1111-111111111115',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Fresh Feeds to Reactor',
        isEditable: true,
        productName: 'Coker LCN',
      },
      {
        normParameterFKId: '11111111-1111-1111-1111-111111111116',
        jan: 0.0,
        feb: 0.0,
        mar: 0.0,
        apr: 0.0,
        may: 0.0,
        jun: 0.0,
        jul: 0.0,
        aug: 0.0,
        sep: 0.0,
        oct: 0.0,
        nov: 0.0,
        dec: 0.0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Fresh Feeds to Reactor',
        isEditable: true,
        productName: 'Total fresh feeds',
      },

      // C. Feed Specifications
      {
        normParameterFKId: '22222222-2222-2222-2222-222222222221',
        jan: 0.0,
        feb: 0.0,
        mar: 0.0,
        apr: 0.0,
        may: 0.0,
        jun: 0.0,
        jul: 0.0,
        aug: 0.0,
        sep: 0.0,
        oct: 0.0,
        nov: 0.0,
        dec: 0.0,
        remarks: 'Placeholder for UOP K',
        auditYear: '2025-26',
        UOM: 'Number',
        normType: 'Feed Specifications',
        isEditable: true,
        productName: 'UOP K',
      },
      {
        normParameterFKId: '22222222-2222-2222-2222-222222222222',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'g',
        normType: 'Feed Specifications',
        isEditable: true,
        productName: 'Density',
      },
      {
        normParameterFKId: '22222222-2222-2222-2222-222222222223',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'ppmwt',
        normType: 'Feed Specifications',
        isEditable: true,
        productName: 'Nitrogen (total)',
      },
      {
        normParameterFKId: '22222222-2222-2222-2222-222222222224',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'wt%',
        normType: 'Feed Specifications',
        isEditable: true,
        productName: 'Conradson Carbon',
      },
      {
        normParameterFKId: '22222222-2222-2222-2222-222222222225',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'ppmwt',
        normType: 'Feed Specifications',
        isEditable: true,
        productName: 'Nickel',
      },
      {
        normParameterFKId: '22222222-2222-2222-2222-222222222226',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'ppmwt',
        normType: 'Feed Specifications',
        isEditable: true,
        productName: 'Vanadium',
      },
      {
        normParameterFKId: '22222222-2222-2222-2222-222222222227',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'ppmwt',
        normType: 'Feed Specifications',
        isEditable: true,
        productName: 'Sodium',
      },

      // E. Product Yields
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333331',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Fuel Gas',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333332',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Propylene (ex FCC)',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333333',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'LPG',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333334',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T/T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Light Naphtha',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333335',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Heart Cut Naphtha',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333336',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Heavy Cracked Naphtha (HCN)',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333337',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T/T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Light Cycle Oil (LCO)',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333338',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Clarified Slurry Oil (CSO)',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333339',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Coke',
      },
      {
        normParameterFKId: '33333333-3333-3333-3333-333333333330',
        jan: 0.0,
        feb: 0.0,
        mar: 0.0,
        apr: 0.0,
        may: 0.0,
        jun: 0.0,
        jul: 0.0,
        aug: 0.0,
        sep: 0.0,
        oct: 0.0,
        nov: 0.0,
        dec: 0.0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Product Yields',
        isEditable: true,
        productName: 'Total',
      },

      // F. Utilities
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444441',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'KWh',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Power Import',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444442',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'M3',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Cooling Water',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444443',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'HP BFW',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444444',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'MP BFW',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444445',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Net HP Steam Import',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444446',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T/T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Net MP Steam Import',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444447',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Net LP steam Export',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444448',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T/T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Cold Clean Condensate',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444449',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Condensate export',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444450',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Utility water',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444451',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'NM3',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Compressed Air',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444452',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'NM3/T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Nitrogen',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444453',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'M3/T',
        normType: 'Utilities',
        isEditable: true,
        productName: 'Desal',
      },
      {
        normParameterFKId: '44444444-4444-4444-4444-444444444454',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'CHEM SODIUM HYDROXIDE (CAUSTIC)',
      },

      // G. Catalyst and Chemicals
      {
        normParameterFKId: '55555555-5555-5555-5555-555555555551',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'kg/kT',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'CHEM MAXTREAT 3223 SJ',
      },
      {
        normParameterFKId: '55555555-5555-5555-5555-555555555552',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'kg',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'CHEM MAX-AMINE 70B',
      },
      {
        normParameterFKId: '55555555-5555-5555-5555-555555555553',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: 'Dry basis',
        auditYear: '2025-26',
        UOM: 'kg/kT',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'CHEM CAT RELIANCE FCC1 X11D2A',
      },
      {
        normParameterFKId: '55555555-5555-5555-5555-555555555554',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'kg',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'CHEM CAT OLEFINS ULTRA MZ ADDITIVE',
      },
      {
        normParameterFKId: '55555555-5555-5555-5555-555555555555',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'kg/kT',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'CHEM CAT CP5/COP550/KOC-15 COMB PROM',
      },
      {
        normParameterFKId: '55555555-5555-5555-5555-555555555556',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'kg',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'VASUFLOC - 4410',
      },
      {
        normParameterFKId: '55555555-5555-5555-5555-555555555557',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg',
        normType: 'Catalyst and Chemicals',
        isEditable: true,
        productName: 'VASUFLOC-1012C',
      },

      // H. TSRF
      {
        normParameterFKId: '66666666-6666-6666-6666-666666666661',
        jan: 3.5,
        feb: 3.5,
        mar: 3.5,
        apr: 3.5,
        may: 3.5,
        jun: 3.5,
        jul: 3.5,
        aug: 3.5,
        sep: 3.5,
        oct: 3.5,
        nov: 3.5,
        dec: 3.5,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'TSRF',
        normType: 'TSRF',
        isEditable: true,
        productName: 'TSRF',
      },
    ],
  }
