export const overAllAOpResponse =
  //OVERALL AOP
  {
    code: 200,
    message: 'Data fetched successfully',
    data: {
      mcuNormsValueDTOList: [
        // A. Feed
        {
          id: 'FCC-A1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'KTPD',
          isEditable: true,
          productName: 'SRFO',
        },
        {
          id: 'FCC-A2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: '%',
          isEditable: true,
          productName: 'Cold feed',
        },
        {
          id: 'FCC-A3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'Wt.%',
          isEditable: true,
          productName: 'CCR (Lab Actual)',
        },
        {
          id: 'FCC-A4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: '-',
          isEditable: true,
          productName: 'Specific Gravity (Lab Actual)',
        },
        {
          id: 'FCC-A5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'Wt.%',
          isEditable: true,
          productName: 'Sulphur (Lab Actual)',
        },
        {
          id: 'FCC-A6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'Wt.%',
          isEditable: true,
          productName: 'Asphaltene (EPS Planning)',
        },
        {
          id: 'FCC-A7',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'wt. ppm',
          isEditable: true,
          productName: 'Nitrogen (EPS Planning)',
        },
        // C. Fuel
        {
          id: 'FCC-C1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'Main Heater COT',
        },
        {
          id: 'FCC-C2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'VR from CDU-1',
        },
        {
          id: 'FCC-C3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'VR From CDU-2',
        },
        {
          id: 'FCC-C4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'VR From RTF',
        },
        {
          id: 'FCC-C5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'Fractionator Bottom Temperature',
        },
        {
          id: 'FCC-C6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: 'SRFT/KT Feed',
          isEditable: true,
          productName: 'Fuel Gas',
        },
        // D. Catalyst & Chemicals
        {
          id: 'FCC-D1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Ammonium Poly Sulfide',
        },
        {
          id: 'FCC-D2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Trisodium Phosphate',
        },
        {
          id: 'FCC-D3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Soda Ash',
        },
        {
          id: 'FCC-D4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'MS-6209 Flowgard',
        },
        {
          id: 'FCC-D5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Dorf Antifoam',
        },
        {
          id: 'FCC-D6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Demulsifier',
        },
        {
          id: 'FCC-D7',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT (HCGO+LCGO+HCN)',
          isEditable: true,
          productName: 'Polyflo 130',
        },
        // E. Power & Utilities
        {
          id: 'FCC-E1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MWH/KT Feed',
          isEditable: true,
          productName: 'Power',
        },
        {
          id: 'FCC-E2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MT/KT Feed',
          isEditable: true,
          productName: 'HP Steam',
        },
        {
          id: 'FCC-E3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MT/KT Feed',
          isEditable: true,
          productName: 'MP Steam',
        },
        {
          id: 'FCC-E4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MT/KT Feed',
          isEditable: true,
          productName: 'LP Steam (Generation)',
        },
        {
          id: 'FCC-E5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'Km3/KT Feed',
          isEditable: true,
          productName: 'Cooling Water',
        },
        {
          id: 'FCC-E6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'Process Water (Clean Cold Condensate)',
        },
        {
          id: 'FCC-E7',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'Boiler Feed Water',
        },
        {
          id: 'FCC-E8',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'Nm3/KT Feed',
          isEditable: true,
          productName: 'Nitrogen',
        },
        {
          id: 'FCC-E9',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'Nm3/KT Feed',
          isEditable: true,
          productName: 'Compressed Air',
        },
        {
          id: 'FCC-E10',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'Utility Water',
        },
        {
          id: 'FCC-E11',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'RO Water',
        },
        // F. Energy Norms
        {
          id: 'FCC-F1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Energy Norms',
          normParameterTypeDisplayName: 'Energy Norms',
          UOM: '-',
          isEditable: true,
          productName: 'Total TRSF/KT',
        },
        {
          id: 'FCC-F2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Energy Norms',
          normParameterTypeDisplayName: 'Energy Norms',
          UOM: '-',
          isEditable: true,
          productName: 'SEI',
        },
        {
          id: 'FCC-F3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Energy Norms',
          normParameterTypeDisplayName: 'Energy Norms',
          UOM: '-',
          isEditable: true,
          productName: 'EII',
        },
      ],
      aopCalculation: [],
    },
  }

export const steadyStateConsumptionResponse =
  //STEAD STA ENORMS

  {
    code: 200,
    message: 'Data fetched successfully',
    data: {
      mcuNormsValueDTOList: [
        // A. Feed
        {
          id: 'FCC-A1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'KTPD',
          isEditable: true,
          productName: 'SRFO',
        },
        {
          id: 'FCC-A2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: '%',
          isEditable: true,
          productName: 'Cold feed',
        },
        {
          id: 'FCC-A3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'Wt.%',
          isEditable: true,
          productName: 'CCR (Lab Actual)',
        },
        {
          id: 'FCC-A4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: '-',
          isEditable: true,
          productName: 'Specific Gravity (Lab Actual)',
        },
        {
          id: 'FCC-A5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'Wt.%',
          isEditable: true,
          productName: 'Sulphur (Lab Actual)',
        },
        {
          id: 'FCC-A6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'Wt.%',
          isEditable: true,
          productName: 'Asphaltene (EPS Planning)',
        },
        {
          id: 'FCC-A7',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Feed',
          normParameterTypeDisplayName: 'Feed',
          UOM: 'wt. ppm',
          isEditable: true,
          productName: 'Nitrogen (EPS Planning)',
        },
        // C. Fuel
        {
          id: 'FCC-C1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'Main Heater COT',
        },
        {
          id: 'FCC-C2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'VR from CDU-1',
        },
        {
          id: 'FCC-C3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'VR From CDU-2',
        },
        {
          id: 'FCC-C4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'VR From RTF',
        },
        {
          id: 'FCC-C5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: '°C',
          isEditable: true,
          productName: 'Fractionator Bottom Temperature',
        },
        {
          id: 'FCC-C6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Fuel',
          normParameterTypeDisplayName: 'Fuel',
          UOM: 'SRFT/KT Feed',
          isEditable: true,
          productName: 'Fuel Gas',
        },
        // D. Catalyst & Chemicals
        {
          id: 'FCC-D1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Ammonium Poly Sulfide',
        },
        {
          id: 'FCC-D2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Trisodium Phosphate',
        },
        {
          id: 'FCC-D3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Soda Ash',
        },
        {
          id: 'FCC-D4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'MS-6209 Flowgard',
        },
        {
          id: 'FCC-D5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Dorf Antifoam',
        },
        {
          id: 'FCC-D6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT Feed',
          isEditable: true,
          productName: 'Demulsifier',
        },
        {
          id: 'FCC-D7',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Catalyst & Chemicals',
          normParameterTypeDisplayName: 'Catalyst & Chemicals',
          UOM: 'Kg/KT (HCGO+LCGO+HCN)',
          isEditable: true,
          productName: 'Polyflo 130',
        },
        // E. Power & Utilities
        {
          id: 'FCC-E1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MWH/KT Feed',
          isEditable: true,
          productName: 'Power',
        },
        {
          id: 'FCC-E2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MT/KT Feed',
          isEditable: true,
          productName: 'HP Steam',
        },
        {
          id: 'FCC-E3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MT/KT Feed',
          isEditable: true,
          productName: 'MP Steam',
        },
        {
          id: 'FCC-E4',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'MT/KT Feed',
          isEditable: true,
          productName: 'LP Steam (Generation)',
        },
        {
          id: 'FCC-E5',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'Km3/KT Feed',
          isEditable: true,
          productName: 'Cooling Water',
        },
        {
          id: 'FCC-E6',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'Process Water (Clean Cold Condensate)',
        },
        {
          id: 'FCC-E7',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'Boiler Feed Water',
        },
        {
          id: 'FCC-E8',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'Nm3/KT Feed',
          isEditable: true,
          productName: 'Nitrogen',
        },
        {
          id: 'FCC-E9',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'Nm3/KT Feed',
          isEditable: true,
          productName: 'Compressed Air',
        },
        {
          id: 'FCC-E10',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'Utility Water',
        },
        {
          id: 'FCC-E11',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Power & Utilities',
          normParameterTypeDisplayName: 'Power & Utilities',
          UOM: 'm3/KT Feed',
          isEditable: true,
          productName: 'RO Water',
        },
        // F. Energy Norms
        {
          id: 'FCC-F1',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Energy Norms',
          normParameterTypeDisplayName: 'Energy Norms',
          UOM: '-',
          isEditable: true,
          productName: 'Total TRSF/KT',
        },
        {
          id: 'FCC-F2',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Energy Norms',
          normParameterTypeDisplayName: 'Energy Norms',
          UOM: '-',
          isEditable: true,
          productName: 'SEI',
        },
        {
          id: 'FCC-F3',
          april: 0,
          may: 0,
          june: 0,
          july: 0,
          august: 0,
          september: 0,
          october: 0,
          november: 0,
          december: 0,
          january: 0,
          february: 0,
          march: 0,
          financialYear: '2025-26',
          remarks: '',
          normParameterTypeName: 'Energy Norms',
          normParameterTypeDisplayName: 'Energy Norms',
          UOM: '-',
          isEditable: true,
          productName: 'EII',
        },
      ],
      aopCalculation: [],
    },
  }

export const monthwiseProductionPlanResponse =
  //MONTH WISE PRODUCTION PLAN

  {
    code: 200,
    message: 'Data fetched successfully',
    data: {
      aopCalculation: [
        {
          id: 'd0b0e843-383f-4248-a97e-09cb3919a8ca',
          plantId: 'aacdbe12-c5f6-4b79-9c88-751169815b42',
          aopYear: '2025-26',
          isChanged: true,
          calculationScreen: 'production-aop',
          updatedScreen: 'shutdown-plan',
        },
      ],
      aopDTOList: [
        {
          id: '158B5A43-369A-4D48-8B7F-4DA9A15A6FED',
          jan: 14673.620599999998,
          feb: 13225.5872,
          march: 14641.6782,
          april: 17136.0,
          may: 14353.979599999999,
          june: 13836.228000000001,
          july: 14282.102999999997,
          aug: 14352.287,
          sep: 13934.807999999999,
          oct: 14198.521525,
          nov: 10416.739999999998,
          dec: 9443.228000000003,
          avgTPH: 165678.6875,
          materialFKId: '00DC05B1-9607-470E-A159-62497E0123E2',
          displayOrder: 1,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'VGO',
          type: 'product',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: 'EBC50FD2-A8E7-487F-8818-E36DC31E10C0',
          jan: 3429.1331999999998,
          feb: 3039.5456,
          march: 3318.2462,
          april: 3225.5879999999997,
          may: 3207.5638,
          june: 3259.506,
          july: 3284.4251999999997,
          aug: 3247.591,
          sep: 3192.7619999999997,
          oct: 3127.8820333333333,
          nov: 11151.582,
          dec: 2211.692,
          avgTPH: 39429.55859375,
          materialFKId: 'A061E050-0281-421F-81C1-B136CE2ED3F3',
          displayOrder: 2,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Diesel',
          type: 'product',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589D',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Kerosene',
          type: 'product',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589DM',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Slops',
          type: 'biproduct',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589DN',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'Off Gas',
          type: 'biproduct',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
        {
          id: '9C5EEB46-D9CD-476E-91F8-062C037A589DO',
          jan: 13877.946349079997,
          feb: 12571.61254272,
          march: 13975.3797744,
          april: 306029.064,
          may: 13756.906380359998,
          june: 13053.7902924,
          july: 13573.333940759996,
          aug: 13705.4158032,
          sep: 13257.833173199997,
          oct: 13663.383260614999,
          nov: -906.941996400003,
          dec: 8925.161731200003,
          avgTPH: 157185.0,
          materialFKId: '92E0AF06-9535-4B93-8998-E56A71354393',
          displayOrder: 3,
          normParameterName: 'Production',
          normParameterDisplayName: 'Production',
          normParameterTypeId: 'BEA7E9B4-05FA-49B3-8B7A-67673C629820',
          displayName: 'H2S',
          type: 'biproduct',
          remark: '',
          isEditable: true,
          isVisible: true,
        },
      ],
    },
  }

//Production and Norms Basis Constatnt
export const productionAndNormsBasisConstant = {
  code: 200,
  message: 'Data fetched successfully',
  data: [
    {
      NormParameter_FK_Id: '75E48C4B-873C-41AF-9EA6-50A2F6BB987F',
      // UOM: 'MT',
      isEditable: true,
      Remarks: '2',
      NormDisplayTypeName: 'Constant',
      DisplayName: 'Allocated Ethyelene Consumptions',
      AuditYear: '2026-27',
      ConstantValue: 0.07292,
      Name: 'A',
    },
    {
      NormParameter_FK_Id: 'C3ECFA4D-843A-4F16-A5B2-1C94B7C15F82',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT.',
      NormTypeName: 'Constant',
      DisplayName: 'BFWFeedTemperature',
      AuditYear: '2026-27',
      ConstantValue: 0.0625,
      Name: 'B',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285DA',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.06355,
      Name: 'D',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285DAP',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0588,
      Name: 'E',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285DAQ',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.05097,
      Name: 'F',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0533,
      Name: 'G',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.28571,
      Name: 'H',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.229,
      Name: 'I',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0625,
      Name: 'HpsConstant',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0588,
      Name: 'MpsConstant',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.0533,
      Name: 'LpsConstant',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 0.229,
      Name: 'Power',
    },
    {
      NormParameter_FK_Id: '3DC7566A-DA7B-46DE-B14B-3065F88285D45R',
      // UOM: 'MT',
      isEditable: true,
      Remarks: 'from DCT',
      NormTypeName: 'Constant',
      DisplayName: 'Condensate temperature in Gas cooler steam drum',
      AuditYear: '2026-27',
      ConstantValue: 10,
      Name: 'Tput',
    },
  ],
}

export const configurationAndReportManualEntryResponse =
  //COMMON CONFIGURATION SCRN + REPORT MANNUAL ENTRy
  {
    code: 200,
    message: 'Data fetched successfully',
    data: [
      // Feed
      {
        normParameterFKId: 'FCC-FEED-001',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'KTPD',
        normType: 'Feed',
        isEditable: true,
        productName: 'SRFO',
      },
      {
        normParameterFKId: 'FCC-FEED-002',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '%',
        normType: 'Feed',
        isEditable: true,
        productName: 'Cold feed',
      },
      {
        normParameterFKId: 'FCC-FEED-003',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Wt.%',
        normType: 'Feed',
        isEditable: true,
        productName: 'CCR (Lab Actual)',
      },
      {
        normParameterFKId: 'FCC-FEED-004',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '-',
        normType: 'Feed',
        isEditable: true,
        productName: 'Specific Gravity (Lab Actual)',
      },
      {
        normParameterFKId: 'FCC-FEED-005',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Wt.%',
        normType: 'Feed',
        isEditable: true,
        productName: 'Sulphur (Lab Actual)',
      },
      {
        normParameterFKId: 'FCC-FEED-006',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Wt.%',
        normType: 'Feed',
        isEditable: true,
        productName: 'Asphaltene (EPS Planning)',
      },
      {
        normParameterFKId: 'FCC-FEED-007',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'wt. ppm',
        normType: 'Feed',
        isEditable: true,
        productName: 'Nitrogen (EPS Planning)',
      },
      // Fuel
      {
        normParameterFKId: 'FCC-FUEL-001',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '°C',
        normType: 'Fuel',
        isEditable: true,
        productName: 'Main Heater COT',
      },
      {
        normParameterFKId: 'FCC-FUEL-002',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '°C',
        normType: 'Fuel',
        isEditable: true,
        productName: 'VR from CDU-1',
      },
      {
        normParameterFKId: 'FCC-FUEL-003',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '°C',
        normType: 'Fuel',
        isEditable: true,
        productName: 'VR From CDU-2',
      },
      {
        normParameterFKId: 'FCC-FUEL-004',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '°C',
        normType: 'Fuel',
        isEditable: true,
        productName: 'VR From RTF',
      },
      {
        normParameterFKId: 'FCC-FUEL-005',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '°C',
        normType: 'Fuel',
        isEditable: true,
        productName: 'Fractionator Bottom Temperature',
      },
      {
        normParameterFKId: 'FCC-FUEL-006',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'SRFT',
        normType: 'Fuel',
        isEditable: true,
        productName: 'Fuel Gas',
      },
      // Catalyst & Chemicals
      {
        normParameterFKId: 'FCC-CHEM-001',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg',
        normType: 'Catalyst & Chemicals',
        isEditable: true,
        productName: 'Ammonium Poly Sulfide',
      },
      {
        normParameterFKId: 'FCC-CHEM-002',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg/KT Feed',
        normType: 'Catalyst & Chemicals',
        isEditable: true,
        productName: 'Trisodium Phosphate',
      },
      {
        normParameterFKId: 'FCC-CHEM-003',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg/KT Feed',
        normType: 'Catalyst & Chemicals',
        isEditable: true,
        productName: 'Soda Ash',
      },
      {
        normParameterFKId: 'FCC-CHEM-004',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg',
        normType: 'Catalyst & Chemicals',
        isEditable: true,
        productName: 'MS-6209 Flowgard',
      },
      {
        normParameterFKId: 'FCC-CHEM-005',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg/KT Feed',
        normType: 'Catalyst & Chemicals',
        isEditable: true,
        productName: 'Dorf Antifoam',
      },
      {
        normParameterFKId: 'FCC-CHEM-006',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg',
        normType: 'Catalyst & Chemicals',
        isEditable: true,
        productName: 'Demulsifier',
      },
      {
        normParameterFKId: 'FCC-CHEM-007',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Kg/KT (HCGO+LCGO+HCN)',
        normType: 'Catalyst & Chemicals',
        isEditable: true,
        productName: 'Polyflo 130',
      },
      // Power & Utilities
      {
        normParameterFKId: 'FCC-UTIL-001',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'MWH',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'Power',
      },
      {
        normParameterFKId: 'FCC-UTIL-002',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'MT',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'HP Steam',
      },
      {
        normParameterFKId: 'FCC-UTIL-003',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'MT',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'MP Steam',
      },
      {
        normParameterFKId: 'FCC-UTIL-004',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'MT',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'LP Steam (Generation)',
      },
      {
        normParameterFKId: 'FCC-UTIL-005',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Km3',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'Cooling Water',
      },
      {
        normParameterFKId: 'FCC-UTIL-006',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'm3/KT Feed',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'Process Water (Clean Cold Condensate)',
      },
      {
        normParameterFKId: 'FCC-UTIL-007',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'm3/KT Feed',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'Boiler Feed Water',
      },
      {
        normParameterFKId: 'FCC-UTIL-008',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Nm3',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'Nitrogen',
      },
      {
        normParameterFKId: 'FCC-UTIL-009',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'Nm3',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'Compressed Air',
      },
      {
        normParameterFKId: 'FCC-UTIL-010',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'm3/KT Feed',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'Utility Water',
      },
      {
        normParameterFKId: 'FCC-UTIL-011',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: 'm3',
        normType: 'Power & Utilities',
        isEditable: true,
        productName: 'RO Water',
      },
      // Energy Norms
      {
        normParameterFKId: 'FCC-ENERGY-001',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '-',
        normType: 'Energy Norms',
        isEditable: true,
        productName: 'Total TRSF/KT',
      },
      {
        normParameterFKId: 'FCC-ENERGY-002',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '-',
        normType: 'Energy Norms',
        isEditable: true,
        productName: 'SEI',
      },
      {
        normParameterFKId: 'FCC-ENERGY-003',
        jan: 0,
        feb: 0,
        mar: 0,
        apr: 0,
        may: 0,
        jun: 0,
        jul: 0,
        aug: 0,
        sep: 0,
        oct: 0,
        nov: 0,
        dec: 0,
        remarks: '',
        auditYear: '2025-26',
        UOM: '-',
        normType: 'Energy Norms',
        isEditable: true,
        productName: 'EII',
      },
    ],
  }
