/**
 * Utility functions for handling field dependencies and calculations
 */

/**
 * Calculate the difference in days between two dates
 * @param {Date|string} startDate - The start date
 * @param {Date|string} endDate - The end date
 * @returns {number} The difference in days (rounded up)
 */
export const calculateDateDifference = (startDate, endDate) => {
  const start = new Date(startDate)
  const end = new Date(endDate)
  const diffTime = end - start
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24))
}

/**
 * Handle date difference calculation dependency
 * @param {Object} params - Parameters object
 * @param {string} params.value - The new value for the field
 * @param {Object} params.dependencyConfig - The dependency configuration
 * @param {Array} params.rows - Current rows data
 * @param {Function} params.setRowsCallback - Callback to update rows
 * @param {Function} params.setModifiedCells - Callback to update modified cells
 * @param {Function} params.setCustomModifiedCells - Callback to update custom modified cells
 */
export const handleDateDifferenceCalculation = ({
  value,
  dependencyConfig,
  rows,
  setRowsCallback,
  setModifiedCells,
  setCustomModifiedCells,
}) => {
  const { dependentProductName, targetDateField } = dependencyConfig

  // Find the target date field
  const targetDateRow = rows.find((r) => r.name === targetDateField)

  if (!targetDateRow || !targetDateRow.attributeValue || !value) {
    return
  }

  // Validate dates
  const startDate = new Date(value)
  const endDate = new Date(targetDateRow.attributeValue)

  if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
    console.error(
      'Invalid date values provided for date difference calculation',
    )
    return
  }

  // Calculate days difference
  const diffDays = calculateDateDifference(value, targetDateRow.attributeValue)

  // Format dates for remark (yyyy-mm-dd format)
  const formatDateString = (date) => {
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    return `${year}-${month}-${day}`
  }
  const startDateFormatted = formatDateString(startDate)
  const endDateFormatted = formatDateString(endDate)

  // Generate remark with warning for negative days
  let autoRemark = `Auto-calculated: ${diffDays} days between ${startDateFormatted} and ${endDateFormatted}`
  if (diffDays < 0) {
    autoRemark += ' (Warning: Preparation date is after cycle start date)'
  }

  // Find dependent row once (performance optimization)
  const dependentRow = rows.find((r) => r.name === dependentProductName)
  if (!dependentRow) {
    console.warn(`Dependent row not found: ${dependentProductName}`)
    return
  }

  // Preserve existing user remarks if they exist and are not auto-generated
  const existingRemark = dependentRow.remarks || ''
  const isAutoGenerated = existingRemark.startsWith('Auto-calculated:')
  const finalRemark =
    isAutoGenerated || !existingRemark
      ? autoRemark
      : `${existingRemark} | ${autoRemark}`

  // Update rows
  setRowsCallback((prevRows) => {
    return prevRows.map((row) => {
      if (row.name === dependentProductName) {
        return {
          ...row,
          attributeValue: diffDays,
          remarks: finalRemark,
          inEdit: true,
        }
      }
      return row
    })
  })

  // Update modifiedCells
  setModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...dependentRow,
        attributeValue: diffDays,
        remarks: finalRemark,
        inEdit: true,
      },
    }
  })

  // Update customModifiedCells for orange highlighting
  setCustomModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...(prev[dependentRow.id] || {}),
        attributeValue: diffDays,
        remarks: finalRemark,
      },
    }
  })
}

/**
 * Handle value mapping dependency (e.g., dropdown changes)
 * @param {Object} params - Parameters object
 * @param {string} params.value - The new value for the field
 * @param {Object} params.dependencyConfig - The dependency configuration
 * @param {Array} params.rows - Current rows data
 * @param {Function} params.setRowsCallback - Callback to update rows
 * @param {Function} params.setModifiedCells - Callback to update modified cells
 * @param {Function} params.setCustomModifiedCells - Callback to update custom modified cells
 * @param {string} params.sourceFieldName - The name of the source field triggering the dependency
 * @param {Object} params.editabilityRules - Rules for controlling field editability based on source values
 */
export const handleValueMappingDependency = ({
  value,
  dependencyConfig,
  rows,
  setRowsCallback,
  setModifiedCells,
  setCustomModifiedCells,
  sourceFieldName,
  editabilityRules,
}) => {
  const { dependentProductName, valueMapping } = dependencyConfig

  const dependentValue = valueMapping[value]
  if (dependentValue === undefined) return

  // Find dependent row to check if it's editable
  const dependentRow = rows.find((r) => r.name === dependentProductName)
  if (!dependentRow) return

  // Check editability rules for the source field
  let shouldBeEditable = dependentRow.isEditable
  if (
    editabilityRules &&
    sourceFieldName &&
    editabilityRules[sourceFieldName]
  ) {
    const rule = editabilityRules[sourceFieldName]
    if (rule.dependentField === dependentProductName) {
      // If source value is in nonEditableWhen list, make dependent field non-editable
      shouldBeEditable = !rule.nonEditableWhen.includes(value)
    }
  }

  // Generate auto-remark for dependency change
  const autoRemark = `Auto-updated`

  // Preserve existing user remarks if they exist and are not auto-generated
  const existingRemark = dependentRow.remarks || ''
  const isAutoGenerated =
    existingRemark === 'Auto-updated' ||
    existingRemark === 'Auto-updated:' ||
    existingRemark.startsWith('Auto-updated:') ||
    existingRemark.startsWith('Auto-calculated:')
  // Only replace if auto-generated, otherwise keep user's remark as-is
  const finalRemark =
    isAutoGenerated || !existingRemark ? autoRemark : existingRemark

  // Update rows
  setRowsCallback((prevRows) => {
    return prevRows.map((row) => {
      if (row.name === dependentProductName) {
        return {
          ...row,
          attributeValue: dependentValue,
          remarks: finalRemark,
          isEditable: shouldBeEditable,
          inEdit: true,
        }
      }
      return row
    })
  })

  // Update modifiedCells
  setModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...dependentRow,
        attributeValue: dependentValue,
        remarks: finalRemark,
        isEditable: shouldBeEditable,
        inEdit: true,
      },
    }
  })

  // Update customModifiedCells
  setCustomModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...(prev[dependentRow.id] || {}),
        attributeValue: dependentValue,
        remarks: finalRemark,
      },
    }
  })
}

/**
 * Handle legacy dependency rules format
 * @param {Object} params - Parameters object
 * @param {string} params.value - The new value for the field
 * @param {Object} params.dependencyRule - The legacy dependency rule
 * @param {Array} params.rows - Current rows data
 * @param {Function} params.setRowsCallback - Callback to update rows
 * @param {Function} params.setModifiedCells - Callback to update modified cells
 * @param {Function} params.setCustomModifiedCells - Callback to update custom modified cells
 * @param {string} params.sourceFieldName - The name of the source field triggering the dependency
 */
export const handleLegacyDependencyRule = ({
  value,
  dependencyRule,
  rows,
  setRowsCallback,
  setModifiedCells,
  setCustomModifiedCells,
  sourceFieldName,
}) => {
  const dependentValue = dependencyRule.values[value]
  if (dependentValue === undefined) return

  // Find dependent row
  const dependentRow = rows.find(
    (r) => r.name === dependencyRule.dependentProductName,
  )
  if (!dependentRow) return

  // Generate auto-remark for dependency change
  const autoRemark = `Auto-updated`

  // Preserve existing user remarks if they exist and are not auto-generated
  const existingRemark = dependentRow.remarks || ''
  const isAutoGenerated =
    existingRemark === 'Auto-updated' ||
    existingRemark === 'Auto-updated:' ||
    existingRemark.startsWith('Auto-updated:') ||
    existingRemark.startsWith('Auto-calculated:')
  // Only replace if auto-generated, otherwise keep user's remark as-is
  const finalRemark =
    isAutoGenerated || !existingRemark ? autoRemark : existingRemark

  // Update rows
  setRowsCallback((prevRows) => {
    return prevRows.map((row) => {
      if (row.name === dependencyRule.dependentProductName) {
        return {
          ...row,
          attributeValue: dependentValue,
          remarks: finalRemark,
          inEdit: true,
        }
      }
      return row
    })
  })

  // Update modifiedCells
  setModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...dependentRow,
        attributeValue: dependentValue,
        remarks: finalRemark,
        inEdit: true,
      },
    }
  })

  // Update customModifiedCells
  setCustomModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...(prev[dependentRow.id] || {}),
        attributeValue: dependentValue,
        remarks: finalRemark,
      },
    }
  })
}

/**
 * Handle addition dependency (sum of multiple fields)
 * @param {Object} params - Parameters object
 * @param {string} params.currentFieldName - The name of the field being changed
 * @param {number} params.value - The new value for the field
 * @param {Object} params.dependencyConfig - The dependency configuration
 * @param {Array} params.rows - Current rows data
 * @param {Function} params.setRowsCallback - Callback to update rows
 * @param {Function} params.setModifiedCells - Callback to update modified cells
 * @param {Function} params.setCustomModifiedCells - Callback to update custom modified cells
 */
export const handleAdditionDependency = ({
  currentFieldName,
  value,
  dependencyConfig,
  rows,
  setRowsCallback,
  setModifiedCells,
  setCustomModifiedCells,
}) => {
  const { sourceFields, targetField } = dependencyConfig

  // Validate that current field is one of the source fields
  if (!sourceFields.includes(currentFieldName)) return

  // Get values from all source fields
  const sourceValues = sourceFields.map((fieldName) => {
    if (fieldName === currentFieldName) {
      return parseFloat(value) || 0
    }
    const sourceRow = rows.find(
      (r) => r.displayName === fieldName || r.name === fieldName,
    )
    return parseFloat(sourceRow?.attributeValue) || 0
  })

  // Calculate sum
  const sum = sourceValues.reduce((acc, val) => acc + val, 0)

  // Find target row
  const targetRow = rows.find(
    (r) => r.displayName === targetField || r.name === targetField,
  )
  if (!targetRow) {
    console.warn(`Target field not found: ${targetField}`)
    return
  }

  // Generate auto-remark
  const autoRemark = `Auto-calculated: Sum of ${sourceFields.join(' + ')}`

  // Preserve existing user remarks if they exist and are not auto-generated
  const existingRemark = targetRow.remarks || ''
  const isAutoGenerated = existingRemark.startsWith('Auto-calculated:')
  const finalRemark =
    isAutoGenerated || !existingRemark
      ? autoRemark
      : `${existingRemark} | ${autoRemark}`

  // Update rows
  setRowsCallback((prevRows) => {
    return prevRows.map((row) => {
      if (row.displayName === targetField || row.name === targetField) {
        return {
          ...row,
          attributeValue: sum,
          remarks: finalRemark,
          inEdit: true,
        }
      }
      return row
    })
  })

  // Update modifiedCells
  setModifiedCells((prev) => {
    return {
      ...prev,
      [targetRow.id]: {
        ...targetRow,
        attributeValue: sum,
        remarks: finalRemark,
        inEdit: true,
      },
    }
  })

  // Update customModifiedCells for orange highlighting
  setCustomModifiedCells((prev) => {
    return {
      ...prev,
      [targetRow.id]: {
        ...(prev[targetRow.id] || {}),
        attributeValue: sum,
        remarks: finalRemark,
      },
    }
  })
}
