/**
 * Utility functions for handling field dependencies and calculations
 */

/**
 * Calculate the difference in days between two dates
 * @param {Date|string} startDate - The start date
 * @param {Date|string} endDate - The end date
 * @returns {number} The difference in days (rounded up)
 */
export const calculateDateDifference = (startDate, endDate) => {
  const start = new Date(startDate)
  const end = new Date(endDate)
  const diffTime = end - start
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24))
}

/**
 * Handle date difference calculation dependency
 * @param {Object} params - Parameters object
 * @param {string} params.value - The new value for the field
 * @param {Object} params.dependencyConfig - The dependency configuration
 * @param {Array} params.rows - Current rows data
 * @param {Function} params.setRowsCallback - Callback to update rows
 * @param {Function} params.setModifiedCells - Callback to update modified cells
 * @param {Function} params.setCustomModifiedCells - Callback to update custom modified cells
 */
export const handleDateDifferenceCalculation = ({
  value,
  dependencyConfig,
  rows,
  setRowsCallback,
  setModifiedCells,
  setCustomModifiedCells,
}) => {
  const { dependentProductName, targetDateField } = dependencyConfig

  // Find the target date field
  const targetDateRow = rows.find((r) => r.name === targetDateField)

  if (!targetDateRow || !targetDateRow.attributeValue || !value) {
    return
  }

  // Validate dates
  const startDate = new Date(value)
  const endDate = new Date(targetDateRow.attributeValue)

  if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
    console.error(
      'Invalid date values provided for date difference calculation',
    )
    return
  }

  // Calculate days difference
  const diffDays = calculateDateDifference(value, targetDateRow.attributeValue)

  // Format dates for remark (yyyy-mm-dd format)
  const formatDateString = (date) => {
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    return `${year}-${month}-${day}`
  }
  const startDateFormatted = formatDateString(startDate)
  const endDateFormatted = formatDateString(endDate)

  // Generate remark with warning for negative days
  let autoRemark = `Auto-calculated: ${diffDays} days between ${startDateFormatted} and ${endDateFormatted}`
  if (diffDays < 0) {
    autoRemark += ' (Warning: Preparation date is after cycle start date)'
  }

  // Find dependent row once (performance optimization)
  const dependentRow = rows.find((r) => r.name === dependentProductName)
  if (!dependentRow) {
    console.warn(`Dependent row not found: ${dependentProductName}`)
    return
  }

  // Preserve existing user remarks if they exist and are not auto-generated
  const existingRemark = dependentRow.remarks || ''
  const isAutoGenerated = existingRemark.startsWith('Auto-calculated:')
  const finalRemark =
    isAutoGenerated || !existingRemark
      ? autoRemark
      : `${existingRemark} | ${autoRemark}`

  // Update rows
  setRowsCallback((prevRows) => {
    return prevRows.map((row) => {
      if (row.name === dependentProductName) {
        return {
          ...row,
          attributeValue: diffDays,
          remarks: finalRemark,
          inEdit: true,
        }
      }
      return row
    })
  })

  // Update modifiedCells
  setModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...dependentRow,
        attributeValue: diffDays,
        remarks: finalRemark,
        inEdit: true,
      },
    }
  })

  // Update customModifiedCells for orange highlighting
  setCustomModifiedCells((prev) => {
    return {
      ...prev,
      [dependentRow.id]: {
        ...(prev[dependentRow.id] || {}),
        attributeValue: diffDays,
        remarks: finalRemark,
      },
    }
  })
}

/**
 * Handle value mapping dependency (e.g., dropdown changes)
 * @param {Object} params - Parameters object
 * @param {string} params.value - The new value for the field
 * @param {Object} params.attributeValue - The dependency configuration
 * @param {Array} params.rows - Current rows data
 * @param {Function} params.setRowsCallback - Callback to update rows
 * @param {Function} params.setModifiedCells - Callback to update modified cells
 * @param {Function} params.setCustomModifiedCells - Callback to update custom modified cells
 */
export const handleValueMappingDependency = ({
  value,
  dependencyConfig,
  rows,
  setRowsCallback,
  setModifiedCells,
  setCustomModifiedCells,
}) => {
  const { dependentProductName, valueMapping } = dependencyConfig

  const dependentValue = valueMapping[value]
  if (dependentValue === undefined) return

  // Update rows
  setRowsCallback((prevRows) => {
    return prevRows.map((row) => {
      if (row.name === dependentProductName) {
        return {
          ...row,
          attributeValue: dependentValue,
          inEdit: true,
        }
      }
      return row
    })
  })

  // Update modifiedCells
  setModifiedCells((prev) => {
    const dependentRow = rows.find((r) => r.name === dependentProductName)
    if (!dependentRow) return prev

    return {
      ...prev,
      [dependentRow.id]: {
        ...dependentRow,
        attributeValue: dependentValue,
        inEdit: true,
      },
    }
  })

  // Update customModifiedCells
  setCustomModifiedCells((prev) => {
    const dependentRow = rows.find((r) => r.name === dependentProductName)
    if (!dependentRow) return prev

    return {
      ...prev,
      [dependentRow.id]: {
        ...(prev[dependentRow.id] || {}),
        attributeValue: dependentValue,
      },
    }
  })
}

/**
 * Handle legacy dependency rules format
 * @param {Object} params - Parameters object
 * @param {string} params.value - The new value for the field
 * @param {Object} params.dependencyRule - The legacy dependency rule
 * @param {Array} params.rows - Current rows data
 * @param {Function} params.setRowsCallback - Callback to update rows
 * @param {Function} params.setModifiedCells - Callback to update modified cells
 * @param {Function} params.setCustomModifiedCells - Callback to update custom modified cells
 */
export const handleLegacyDependencyRule = ({
  value,
  dependencyRule,
  rows,
  setRowsCallback,
  setModifiedCells,
  setCustomModifiedCells,
}) => {
  const dependentValue = dependencyRule.values[value]
  if (dependentValue === undefined) return

  // Update rows
  setRowsCallback((prevRows) => {
    return prevRows.map((row) => {
      if (row.name === dependencyRule.dependentProductName) {
        return {
          ...row,
          attributeValue: dependentValue,
          inEdit: true,
        }
      }
      return row
    })
  })

  // Update modifiedCells
  setModifiedCells((prev) => {
    const dependentRow = rows.find(
      (r) => r.name === dependencyRule.dependentProductName,
    )
    if (!dependentRow) return prev

    return {
      ...prev,
      [dependentRow.id]: {
        ...dependentRow,
        attributeValue: dependentValue,
        inEdit: true,
      },
    }
  })

  // Update customModifiedCells
  setCustomModifiedCells((prev) => {
    const dependentRow = rows.find(
      (r) => r.name === dependencyRule.dependentProductName,
    )
    if (!dependentRow) return prev

    return {
      ...prev,
      [dependentRow.id]: {
        ...(prev[dependentRow.id] || {}),
        attributeValue: dependentValue,
      },
    }
  })
}
