export const ibrGridOne = [
  {
    field: 'Furnace',
    title: 'Furnace',
    type: 'string',
    width: 200,
    editable: true,
  },
  {
    field: 'MonthNameDropdown',
    title: 'Month Name',
    type: 'string',
    width: 120,
    editable: true,
  },
  {
    field: 'days',
    title: 'Apr-Mar',
    type: 'number',
    width: 100,
    editable: true,
  },
  {
    field: 'Remarks',
    title: 'Remarks',
    type: 'string',
    width: 300,
    editable: true,
  },
]

export const ibrPlanColumns = [
  { field: 'furnace', title: 'Furnace', editable: false, width: 200 },
  {
    field: 'startDateIBR',
    title: 'Start Date of IBR',
    editable: true,
    width: 200,
  },
  { field: 'endDateIBR', title: 'End Date of IBR', editable: true, width: 200 },
  {
    field: 'startDateSD',
    title: 'Start Date of SD',
    editable: true,
    width: 200,
  },
  { field: 'endDateSD', title: 'End Date of SD', editable: true, width: 200 },
  { field: 'startDateTA', title: 'Start date TA', editable: true, width: 200 },
  { field: 'endDateTA', title: 'End date TA', editable: true, width: 200 },
  { field: 'remarks', title: 'Remarks', editable: true, width: 250 },
]

export const ibrGridThree = [
  {
    field: 'Month',
    title: 'Month',
    type: 'string',
    width: 80,
    headerAlign: 'left',
    editable: true,
  },
  {
    field: 'Date',
    title: 'Date',
    type: 'date',
    format: '{0:dd-MMM-yy}',
    width: 100,
    headerAlign: 'left',
    editable: true,
  },
  {
    field: 'H10ActualRunLength',
    title: 'H10 – Actual run length',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H10ProposedAOP',
    title: 'H10 – Proposed AOP',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H11ActualRunLength',
    title: 'H11 – Actual run length',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H11ProposedAOP',
    title: 'H11 – Proposed AOP',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H12ActualRunLength',
    title: 'H12 – Actual run length',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H12ProposedAOP',
    title: 'H12 – Proposed AOP',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H13ActualRunLength',
    title: 'H13 – Actual run length',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H13ProposedAOP',
    title: 'H13 – Proposed AOP',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H14ActualRunLength',
    title: 'H14 – Actual run length',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'H14ProposedAOP',
    title: 'H14 – Proposed AOP',
    type: 'number',
    format: '{0:n0}',
    width: 120,
    align: 'right',
    headerAlign: 'right',
    editable: true,
  },
  {
    field: 'DEMO',
    title: 'DEMO',
    type: 'string',
    width: 80,
    headerAlign: 'center',
    editable: true,
  },
]

export const runningDurationColumns = [
  { field: 'month', title: 'Month', editable: false },
  { field: 'ibr', title: 'IBR', editable: true, type: 'number' },
  { field: 'mnt', title: 'MNT', editable: true, type: 'number' },
  {
    field: 'shutdown',
    title: 'Shutdown',
    editable: true,
    width: 120,
    type: 'number',
  },
  {
    field: 'slowdown',
    title: 'Slowdown',
    editable: true,
    width: 120,
    type: 'number',
  },
  { field: 'sad', title: 'SAD', editable: true, type: 'number' },
  { field: 'buD', title: 'BUD', editable: true, type: 'number' },
  { field: 'fourF', title: '4F', editable: true, type: 'number' },
  { field: 'fiveF', title: '5F', editable: true, type: 'number' },
  { field: 'fourFD', title: '4FD', editable: true, type: 'number' },
  { field: 'total', title: 'Total', editable: false, type: 'number' },
  { field: 'remarks', title: 'Remarks', editable: true, width: 250 },
]
