server:
   port: 7101

logging:
   level:
      root: INFO
      
spring.mvc.converters.preferred-json-mapper: gson


camunda7.rest.deployment.url: /deployment
camunda7.rest.processdefinition.url: /process-definition
camunda7.rest.processinstance.url: /process-instance
camunda7.rest.task.url: /task
camunda7.rest.correlate.url: /message

spring.data.mongodb.uri: ${MONGO_CONN:mongodb://localhost}
spring.data.mongodb.database: ${MONGO_SHARED_DATABASE:shared}
spring.data.mongodb.database.tenant: ${MONGO_DATABASE:localhost}

mongo.data.import.enabled: true
mongo.data.import.folder: ${IMPORT_DIR_PATH:./data}

keycloak.data.import.enabled: true
keycloak.data.import.url: ${KEYCLOAK_URL:http://localhost:8082}
keycloak.data.import.admin: ${KEYCLOAK_ADMIN:admin}
keycloak.data.import.adminpass: ${KEYCLOAK_PASS:admin}
keycloak.data.import.portal-clientid: wks-portal
keycloak.data.import.externaltasks-clientid: wks-external-tasks
keycloak.data.import.externaltasks-secret: ${KEYCLOAK_EXTERNALTASKS_SECRET:123456789}
keycloak.data.import.realm: ${spring.data.mongodb.database.tenant}
keycloak.data.import.dns: localhost
keycloak.data.import.port: :3001
keycloak.data.import.protocol: http://
keycloak.data.import.redirecturl: ${keycloak.data.import.protocol}${keycloak.data.import.dns}${keycloak.data.import.port}/*
keycloak.data.import.weborigins: ${keycloak.data.import.protocol}${keycloak.data.import.dns}${keycloak.data.import.port}
keycloak.data.import.username: ${KEYCLOAK_DEFAULT_USER:demo}
keycloak.data.import.password: ${KEYCLOAK_DEFAULT_USER_PASSWORD:demo}
keycloak.data.import.firstname: ${KEYCLOAK_DEFAULT_USER_FIRST_NAME:demo}
keycloak.data.import.lastname: ${KEYCLOAK_DEFAULT_USER_LAST_NAME:demo}
keycloak.data.import.email: ${KEYCLOAK_DEFAULT_USER_EMAIL:demo@demo.com}

camunda.data.import.enabled: true
camunda.data.import.url: ${CAMUNDA_URL:http://localhost:8080/engine-rest}
camunda.data.import.folder: ${IMPORT_DIR_PATH:./data}
camunda.data.import.tenant: ${spring.data.mongodb.database.tenant}
