// Tab ID to display name mapping
export const TAB_ID_MAP = {
  'purchase-power': 'Purchase Power Input',
  'export-availability': 'Export Availability',
  'shutdown-operational': 'Shutdown and Operational Hrs.',
  'asset-priority': 'Asset Priority',
  'asset-capacity': 'Asset Capacity',
}

// Column definitions for each tab
export const getColumnsForTab = (tabId, headerMap, valueFormat) => {
  const defaultHeaderMap = {
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec',
  }
  const finalHeaderMap = { ...defaultHeaderMap, ...headerMap }

  switch (tabId) {
    case 'purchase-power':
      return [
        { field: 'id', title: 'ID', hidden: true },
        {
          field: 'assetName',
          title: 'Plant',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'utility',
          title: 'Utility',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'uom',
          title: 'UOM',
          widthT: 60,
          minWidth: 80,
          type: 'text',
          editable: false,
        },
        {
          field: finalHeaderMap[4],
          title: finalHeaderMap[4],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[5],
          title: finalHeaderMap[5],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[6],
          title: finalHeaderMap[6],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[7],
          title: finalHeaderMap[7],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[8],
          title: finalHeaderMap[8],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[9],
          title: finalHeaderMap[9],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[10],
          title: finalHeaderMap[10],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[11],
          title: finalHeaderMap[11],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[12],
          title: finalHeaderMap[12],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[1],
          title: finalHeaderMap[1],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[2],
          title: finalHeaderMap[2],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
        {
          field: finalHeaderMap[3],
          title: finalHeaderMap[3],
          editable: true,
          widthT: 100,
          minWidth: 80,
          type: 'number1',
          format: valueFormat,
        },
      ]
    case 'asset-priority':
      return [
        { field: 'id', title: 'ID', hidden: true },
        {
          field: 'assetName',
          title: 'Plant',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'utility',
          title: 'Utility',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'priority',
          title: 'Priority',
          width: 100,
          minWidth: 100,
          type: 'text',
          editable: true,
        },
        {
          field: 'remarks',
          title: 'Remarks',
          width: 300,
          minWidth: 200,
          type: 'text',
          editable: true,
        },
      ]
    case 'export-availability':
      return [
        { field: 'id', title: 'ID', hidden: true },
        {
          field: 'assetName',
          title: 'Plant',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'utility',
          title: 'Utility',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'availability',
          title: 'Availability (%)',
          width: 120,
          minWidth: 100,
          type: 'number',
          editable: true,
        },
      ]
    case 'shutdown-operational':
      return [
        { field: 'id', title: 'ID', hidden: true },
        {
          field: 'assetName',
          title: 'Plant',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'shutdownHrs',
          title: 'Shutdown Hours',
          width: 120,
          minWidth: 100,
          type: 'number',
          editable: true,
        },
        {
          field: 'operationalHrs',
          title: 'Operational Hours',
          width: 120,
          minWidth: 100,
          type: 'number',
          editable: true,
        },
      ]
    case 'asset-capacity':
      return [
        { field: 'id', title: 'ID', hidden: true },
        {
          field: 'assetName',
          title: 'Plant',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'utility',
          title: 'Utility',
          width: 150,
          minWidth: 150,
          type: 'text',
          editable: false,
        },
        {
          field: 'minCapacity',
          title: 'Min Capacity',
          width: 120,
          minWidth: 100,
          type: 'number',
          editable: true,
        },
        {
          field: 'maxCapacity',
          title: 'Max Capacity',
          width: 120,
          minWidth: 100,
          type: 'number',
          editable: true,
        },
        {
          field: 'uom',
          title: 'UOM',
          widthT: 60,
          minWidth: 80,
          type: 'text',
          editable: false,
        },
      ]
    default:
      return []
  }
}

// Mock data for each tab
export const generateMockData = (tabId) => {
  switch (tabId) {
    case 'purchase-power':
      return [
        {
          id: 1,
          assetName: 'Power from MEL',
          utility: 'Power_Dis',
          uom: 'MW',
          'Apr-25': 25.0,
          'May-25': 25.0,
          'Jun-25': 33.0,
          'Jul-25': 33.0,
          'Aug-25': 33.0,
          'Sep-25': 33.0,
          'Oct-25': 33.0,
          'Nov-25': 33.0,
          'Dec-25': 33.0,
          'Jan-26': 33.0,
          'Feb-26': 33.0,
          'Mar-26': 33.0,
        },
        {
          id: 2,
          assetName: 'NMD - Power Plant 1',
          utility: 'POWERGEN',
          uom: 'MW',
          'Apr-25': 12.81,
          'May-25': 7.63,
          'Jun-25': 8.14,
          'Jul-25': 9.45,
          'Aug-25': 10.79,
          'Sep-25': 9.89,
          'Oct-25': 7.76,
          'Nov-25': 9.94,
          'Dec-25': 7.94,
          'Jan-26': 10.63,
          'Feb-26': 11.03,
          'Mar-26': 0,
        },
        {
          id: 3,
          assetName: 'NMD - Power Plant 2',
          utility: 'POWERGEN',
          uom: 'MW',
          'Apr-25': 11.2,
          'May-25': 11.6,
          'Jun-25': 12.5,
          'Jul-25': 6.93,
          'Aug-25': 8.45,
          'Sep-25': 9.3,
          'Oct-25': 10.15,
          'Nov-25': 11.8,
          'Dec-25': 12.4,
          'Jan-26': 13.2,
          'Feb-26': 12.9,
          'Mar-26': 11.5,
        },
        {
          id: 4,
          assetName: 'NMD - Power Plant 3',
          utility: 'POWERGEN',
          uom: 'MW',
          'Apr-25': 12.57,
          'May-25': 13.45,
          'Jun-25': 6.41,
          'Jul-25': 7.89,
          'Aug-25': 7.9,
          'Sep-25': 9.19,
          'Oct-25': 8.29,
          'Nov-25': 6.77,
          'Dec-25': 8.39,
          'Jan-26': 6.39,
          'Feb-26': 9.04,
          'Mar-26': 9.44,
        },
        {
          id: 5,
          assetName: 'NMD - STG Power Plant',
          utility: 'POWERGEN',
          uom: 'MW',
          'Apr-25': 14.21,
          'May-25': 14.21,
          'Jun-25': 12.24,
          'Jul-25': 12.3,
          'Aug-25': 11.92,
          'Sep-25': 11.84,
          'Oct-25': 11.92,
          'Nov-25': 12.24,
          'Dec-25': 11.92,
          'Jan-26': 11.92,
          'Feb-26': 11.67,
          'Mar-26': 11.92,
        },
      ]
    case 'asset-priority':
      return [
        {
          id: 1,
          assetName: 'Power from MEL',
          utility: 'Power_Dis',
          priority: 'High',
          remarks: 'Critical power source - Essential for operations',
        },
        {
          id: 2,
          assetName: 'NMD - Power Plant 1',
          utility: 'POWERGEN',
          priority: 'High',
          remarks: 'Primary internal generation source',
        },
        {
          id: 3,
          assetName: 'NMD - Power Plant 2',
          utility: 'POWERGEN',
          priority: 'Medium',
          remarks: 'Secondary generation source',
        },
        {
          id: 4,
          assetName: 'NMD - Power Plant 3',
          utility: 'POWERGEN',
          priority: 'Medium',
          remarks: 'Backup generation capacity',
        },
        {
          id: 5,
          assetName: 'NMD - STG Power Plant',
          utility: 'POWERGEN',
          priority: 'Low',
          remarks: 'Standby generation facility',
        },
      ]
    case 'export-availability':
      return [
        {
          id: 1,
          assetName: 'Power from MEL',
          utility: 'Power_Dis',
          availability: 95.5,
        },
        {
          id: 2,
          assetName: 'NMD - Power Plant 1',
          utility: 'POWERGEN',
          availability: 88.0,
        },
        {
          id: 3,
          assetName: 'NMD - Power Plant 2',
          utility: 'POWERGEN',
          availability: 92.3,
        },
        {
          id: 4,
          assetName: 'NMD - Power Plant 3',
          utility: 'POWERGEN',
          availability: 85.7,
        },
        {
          id: 5,
          assetName: 'NMD - STG Power Plant',
          utility: 'POWERGEN',
          availability: 78.5,
        },
      ]
    case 'shutdown-operational':
      return [
        {
          id: 1,
          assetName: 'Power from MEL',
          shutdownHrs: 120,
          operationalHrs: 8640,
        },
        {
          id: 2,
          assetName: 'NMD - Power Plant 1',
          shutdownHrs: 240,
          operationalHrs: 8520,
        },
        {
          id: 3,
          assetName: 'NMD - Power Plant 2',
          shutdownHrs: 180,
          operationalHrs: 8580,
        },
        {
          id: 4,
          assetName: 'NMD - Power Plant 3',
          shutdownHrs: 360,
          operationalHrs: 8400,
        },
        {
          id: 5,
          assetName: 'NMD - STG Power Plant',
          shutdownHrs: 720,
          operationalHrs: 8040,
        },
      ]
    case 'asset-capacity':
      return [
        {
          id: 1,
          assetName: 'Power from MEL',
          utility: 'Power_Dis',
          minCapacity: 20.0,
          maxCapacity: 50.0,
          uom: 'MW',
        },
        {
          id: 2,
          assetName: 'NMD - Power Plant 1',
          utility: 'POWERGEN',
          minCapacity: 10.0,
          maxCapacity: 30.0,
          uom: 'MW',
        },
        {
          id: 3,
          assetName: 'NMD - Power Plant 2',
          utility: 'POWERGEN',
          minCapacity: 8.0,
          maxCapacity: 28.0,
          uom: 'MW',
        },
        {
          id: 4,
          assetName: 'NMD - Power Plant 3',
          utility: 'POWERGEN',
          minCapacity: 12.0,
          maxCapacity: 35.0,
          uom: 'MW',
        },
        {
          id: 5,
          assetName: 'NMD - STG Power Plant',
          utility: 'POWERGEN',
          minCapacity: 5.0,
          maxCapacity: 20.0,
          uom: 'MW',
        },
      ]
    default:
      return []
  }
}
